/**
 * AS24 API v4.1
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package abtlibrary.utils.as24ApiClient.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import abtlibrary.utils.as24ApiClient.model.AdDocument;
import abtlibrary.utils.as24ApiClient.model.AdEquipment;
import abtlibrary.utils.as24ApiClient.model.AdImages;
import abtlibrary.utils.as24ApiClient.model.AdUser;
import abtlibrary.utils.as24ApiClient.model.AdVideo;
import abtlibrary.utils.as24ApiClient.model.Insurance;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;


/**
 * Ad
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-21T15:07:04.675+07:00")
public class Ad   {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("certificationCode")
  private String certificationCode = null;

  @SerializedName("chassisCode")
  private String chassisCode = null;

  @SerializedName("customerVehicleCode")
  private String customerVehicleCode = null;

  @SerializedName("userId")
  private Integer userId = null;

  @SerializedName("userTypeId")
  private Integer userTypeId = null;

  @SerializedName("accountId")
  private Integer accountId = null;

  @SerializedName("addressId")
  private Integer addressId = null;

  @SerializedName("seller")
  private AdUser seller = null;

  @SerializedName("status")
  private Integer status = null;

  @SerializedName("dateCreated")
  private DateTime dateCreated = null;

  @SerializedName("dateModified")
  private DateTime dateModified = null;

  @SerializedName("dateValidFrom")
  private DateTime dateValidFrom = null;

  @SerializedName("dateValidTo")
  private DateTime dateValidTo = null;

  @SerializedName("isOnline")
  private Boolean isOnline = null;

  @SerializedName("vehicleVisibilityId")
  private Integer vehicleVisibilityId = null;

  @SerializedName("vehicleTypeGroupId")
  private Integer vehicleTypeGroupId = null;

  @SerializedName("vehicleTypeId")
  private Integer vehicleTypeId = null;

  @SerializedName("vehicleType")
  private String vehicleType = null;

  @SerializedName("makeId")
  private Integer makeId = null;

  @SerializedName("make")
  private String make = null;

  @SerializedName("modelId")
  private Integer modelId = null;

  @SerializedName("model")
  private String model = null;

  @SerializedName("typeName")
  private String typeName = null;

  @SerializedName("typeNameFull")
  private String typeNameFull = null;

  @SerializedName("dateLastInspection")
  private DateTime dateLastInspection = null;

  @SerializedName("firstRegYear")
  private Integer firstRegYear = null;

  @SerializedName("firstRegMonth")
  private Integer firstRegMonth = null;

  @SerializedName("modelYear")
  private Integer modelYear = null;

  @SerializedName("modelMonth")
  private Integer modelMonth = null;

  @SerializedName("conditionTypeId")
  private Integer conditionTypeId = null;

  @SerializedName("conditionType")
  private String conditionType = null;

  @SerializedName("bodyTypeId")
  private Integer bodyTypeId = null;

  @SerializedName("bodyType")
  private String bodyType = null;

  @SerializedName("segmentationTypeId")
  private Integer segmentationTypeId = null;

  @SerializedName("segmentationType")
  private String segmentationType = null;

  @SerializedName("fuelTypeId")
  private Integer fuelTypeId = null;

  @SerializedName("fuelType")
  private String fuelType = null;

  @SerializedName("transmissionTypeId")
  private Integer transmissionTypeId = null;

  @SerializedName("transmissionType")
  private String transmissionType = null;

  @SerializedName("transmissionShaftId")
  private Integer transmissionShaftId = null;

  @SerializedName("transmissionShaftType")
  private String transmissionShaftType = null;

  @SerializedName("driveTypeId")
  private Integer driveTypeId = null;

  @SerializedName("driveType")
  private String driveType = null;

  @SerializedName("pollutionNormTypeId")
  private Integer pollutionNormTypeId = null;

  @SerializedName("pollutionNormType")
  private String pollutionNormType = null;

  @SerializedName("licenseCategoryTypeId")
  private Integer licenseCategoryTypeId = null;

  @SerializedName("licenseCategoryType")
  private String licenseCategoryType = null;

  @SerializedName("consumptionRatingTypeId")
  private Integer consumptionRatingTypeId = null;

  @SerializedName("consumptionRatingType")
  private String consumptionRatingType = null;

  @SerializedName("cylinderDesignTypeId")
  private Integer cylinderDesignTypeId = null;

  @SerializedName("cylinderDesignType")
  private String cylinderDesignType = null;

  @SerializedName("bodyColorId")
  private Integer bodyColorId = null;

  @SerializedName("bodyColor")
  private String bodyColor = null;

  @SerializedName("interiorColorId")
  private Integer interiorColorId = null;

  @SerializedName("interiorColor")
  private String interiorColor = null;

  @SerializedName("price")
  private Double price = null;

  @SerializedName("priceNew")
  private Double priceNew = null;

  @SerializedName("priceOriginal")
  private Double priceOriginal = null;

  @SerializedName("km")
  private Integer km = null;

  @SerializedName("consumptionCity")
  private Double consumptionCity = null;

  @SerializedName("consumptionLand")
  private Double consumptionLand = null;

  @SerializedName("consumptionTotal")
  private Double consumptionTotal = null;

  @SerializedName("consumptionGasCity")
  private Double consumptionGasCity = null;

  @SerializedName("consumptionGasLand")
  private Double consumptionGasLand = null;

  @SerializedName("consumptionGasTotal")
  private Double consumptionGasTotal = null;

  @SerializedName("consumptionPower")
  private Double consumptionPower = null;

  @SerializedName("petrolEquivalent")
  private Double petrolEquivalent = null;

  @SerializedName("co2Emission")
  private Integer co2Emission = null;

  @SerializedName("co2EmissionAverage")
  private Integer co2EmissionAverage = null;

  @SerializedName("co2EmissionPowerProduction")
  private Double co2EmissionPowerProduction = null;

  @SerializedName("doors")
  private Integer doors = null;

  @SerializedName("seats")
  private Integer seats = null;

  @SerializedName("cylinders")
  private Integer cylinders = null;

  @SerializedName("gears")
  private Integer gears = null;

  @SerializedName("ccm")
  private Integer ccm = null;

  @SerializedName("hp")
  private Double hp = null;

  @SerializedName("kw")
  private Double kw = null;

  @SerializedName("weightKerb")
  private Integer weightKerb = null;

  @SerializedName("weightTotal")
  private Integer weightTotal = null;

  @SerializedName("trailerLoadBreaked")
  private Integer trailerLoadBreaked = null;

  @SerializedName("length")
  private Integer length = null;

  @SerializedName("width")
  private Integer width = null;

  @SerializedName("height")
  private Integer height = null;

  @SerializedName("bootHeight")
  private Integer bootHeight = null;

  @SerializedName("bootWidth")
  private Integer bootWidth = null;

  @SerializedName("bootLength")
  private Integer bootLength = null;

  @SerializedName("bootVolume")
  private Integer bootVolume = null;

  @SerializedName("payLoad")
  private Integer payLoad = null;

  @SerializedName("wheelbase")
  private Integer wheelbase = null;

  @SerializedName("axis")
  private Integer axis = null;

  @SerializedName("sleepingBerths")
  private Integer sleepingBerths = null;

  @SerializedName("isBodyColorMetallic")
  private Boolean isBodyColorMetallic = null;

  @SerializedName("bitwiseEquipments")
  private Long bitwiseEquipments = null;

  @SerializedName("originalTextBodyColor")
  private String originalTextBodyColor = null;

  @SerializedName("originalTextInteriorColor")
  private String originalTextInteriorColor = null;

  @SerializedName("originalTextLanguage")
  private String originalTextLanguage = null;

  @SerializedName("teaser")
  private String teaser = null;

  @SerializedName("dateNewRelevant")
  private DateTime dateNewRelevant = null;

  @SerializedName("isBehaveAsNew")
  private Boolean isBehaveAsNew = null;

  @SerializedName("dateNewFlagExpires")
  private DateTime dateNewFlagExpires = null;

  @SerializedName("seoDetail")
  private String seoDetail = null;

  @SerializedName("dateTopListing")
  private DateTime dateTopListing = null;

  @SerializedName("insurance")
  private Insurance insurance = null;

  @SerializedName("showCashSentinel")
  private Boolean showCashSentinel = null;

  @SerializedName("images")
  private AdImages images = null;

  @SerializedName("documents")
  private List<AdDocument> documents = new ArrayList<AdDocument>();

  @SerializedName("videos")
  private List<AdVideo> videos = new ArrayList<AdVideo>();

  @SerializedName("logoId")
  private Integer logoId = null;

  @SerializedName("logoText")
  private String logoText = null;

  @SerializedName("logoUrl")
  private String logoUrl = null;

  @SerializedName("logoImageUrl")
  private String logoImageUrl = null;

  @SerializedName("logoTrackingUrl")
  private String logoTrackingUrl = null;

  @SerializedName("isAccidentVehicle")
  private Boolean isAccidentVehicle = null;

  @SerializedName("isExchangeable")
  private Boolean isExchangeable = null;

  @SerializedName("isExport")
  private Boolean isExport = null;

  @SerializedName("isHandicapConverted")
  private Boolean isHandicapConverted = null;

  @SerializedName("isInspected")
  private Boolean isInspected = null;

  @SerializedName("isDirectImport")
  private Boolean isDirectImport = null;

  @SerializedName("isLocationExact")
  private Boolean isLocationExact = null;

  @SerializedName("isLeasable")
  private Boolean isLeasable = null;

  @SerializedName("isRacingVehicle")
  private Boolean isRacingVehicle = null;

  @SerializedName("isThrottleKitAvailable")
  private Boolean isThrottleKitAvailable = null;

  @SerializedName("isThrottleKitPossible")
  private Boolean isThrottleKitPossible = null;

  @SerializedName("isTuned")
  private Boolean isTuned = null;

  @SerializedName("equipment")
  private AdEquipment equipment = null;

  @SerializedName("longitude")
  private Double longitude = null;

  @SerializedName("latitude")
  private Double latitude = null;

  @SerializedName("comments")
  private String comments = null;

  @SerializedName("internalComments")
  private String internalComments = null;

  @SerializedName("hasWarranty")
  private Boolean hasWarranty = null;

  @SerializedName("warrantyInMonths")
  private Integer warrantyInMonths = null;

  @SerializedName("warrantyDescription")
  private String warrantyDescription = null;

  @SerializedName("isHighlighted")
  private Boolean isHighlighted = null;

  public Ad id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Ad certificationCode(String certificationCode) {
    this.certificationCode = certificationCode;
    return this;
  }

   /**
   * Get certificationCode
   * @return certificationCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCertificationCode() {
    return certificationCode;
  }

  public void setCertificationCode(String certificationCode) {
    this.certificationCode = certificationCode;
  }

  public Ad chassisCode(String chassisCode) {
    this.chassisCode = chassisCode;
    return this;
  }

   /**
   * Get chassisCode
   * @return chassisCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getChassisCode() {
    return chassisCode;
  }

  public void setChassisCode(String chassisCode) {
    this.chassisCode = chassisCode;
  }

  public Ad customerVehicleCode(String customerVehicleCode) {
    this.customerVehicleCode = customerVehicleCode;
    return this;
  }

   /**
   * Get customerVehicleCode
   * @return customerVehicleCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCustomerVehicleCode() {
    return customerVehicleCode;
  }

  public void setCustomerVehicleCode(String customerVehicleCode) {
    this.customerVehicleCode = customerVehicleCode;
  }

  public Ad userId(Integer userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getUserId() {
    return userId;
  }

  public void setUserId(Integer userId) {
    this.userId = userId;
  }

  public Ad userTypeId(Integer userTypeId) {
    this.userTypeId = userTypeId;
    return this;
  }

   /**
   * Get userTypeId
   * @return userTypeId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getUserTypeId() {
    return userTypeId;
  }

  public void setUserTypeId(Integer userTypeId) {
    this.userTypeId = userTypeId;
  }

  public Ad accountId(Integer accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * Get accountId
   * @return accountId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getAccountId() {
    return accountId;
  }

  public void setAccountId(Integer accountId) {
    this.accountId = accountId;
  }

  public Ad addressId(Integer addressId) {
    this.addressId = addressId;
    return this;
  }

   /**
   * Get addressId
   * @return addressId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getAddressId() {
    return addressId;
  }

  public void setAddressId(Integer addressId) {
    this.addressId = addressId;
  }

  public Ad seller(AdUser seller) {
    this.seller = seller;
    return this;
  }

   /**
   * Get seller
   * @return seller
  **/
  @ApiModelProperty(example = "null", value = "")
  public AdUser getSeller() {
    return seller;
  }

  public void setSeller(AdUser seller) {
    this.seller = seller;
  }

  public Ad status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public Ad dateCreated(DateTime dateCreated) {
    this.dateCreated = dateCreated;
    return this;
  }

   /**
   * Get dateCreated
   * @return dateCreated
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getDateCreated() {
    return dateCreated;
  }

  public void setDateCreated(DateTime dateCreated) {
    this.dateCreated = dateCreated;
  }

  public Ad dateModified(DateTime dateModified) {
    this.dateModified = dateModified;
    return this;
  }

   /**
   * Get dateModified
   * @return dateModified
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getDateModified() {
    return dateModified;
  }

  public void setDateModified(DateTime dateModified) {
    this.dateModified = dateModified;
  }

  public Ad dateValidFrom(DateTime dateValidFrom) {
    this.dateValidFrom = dateValidFrom;
    return this;
  }

   /**
   * Get dateValidFrom
   * @return dateValidFrom
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getDateValidFrom() {
    return dateValidFrom;
  }

  public void setDateValidFrom(DateTime dateValidFrom) {
    this.dateValidFrom = dateValidFrom;
  }

  public Ad dateValidTo(DateTime dateValidTo) {
    this.dateValidTo = dateValidTo;
    return this;
  }

   /**
   * Get dateValidTo
   * @return dateValidTo
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getDateValidTo() {
    return dateValidTo;
  }

  public void setDateValidTo(DateTime dateValidTo) {
    this.dateValidTo = dateValidTo;
  }

  public Ad isOnline(Boolean isOnline) {
    this.isOnline = isOnline;
    return this;
  }

   /**
   * Get isOnline
   * @return isOnline
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsOnline() {
    return isOnline;
  }

  public void setIsOnline(Boolean isOnline) {
    this.isOnline = isOnline;
  }

  public Ad vehicleVisibilityId(Integer vehicleVisibilityId) {
    this.vehicleVisibilityId = vehicleVisibilityId;
    return this;
  }

   /**
   * Get vehicleVisibilityId
   * @return vehicleVisibilityId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getVehicleVisibilityId() {
    return vehicleVisibilityId;
  }

  public void setVehicleVisibilityId(Integer vehicleVisibilityId) {
    this.vehicleVisibilityId = vehicleVisibilityId;
  }

  public Ad vehicleTypeGroupId(Integer vehicleTypeGroupId) {
    this.vehicleTypeGroupId = vehicleTypeGroupId;
    return this;
  }

   /**
   * Get vehicleTypeGroupId
   * @return vehicleTypeGroupId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getVehicleTypeGroupId() {
    return vehicleTypeGroupId;
  }

  public void setVehicleTypeGroupId(Integer vehicleTypeGroupId) {
    this.vehicleTypeGroupId = vehicleTypeGroupId;
  }

  public Ad vehicleTypeId(Integer vehicleTypeId) {
    this.vehicleTypeId = vehicleTypeId;
    return this;
  }

   /**
   * Get vehicleTypeId
   * @return vehicleTypeId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getVehicleTypeId() {
    return vehicleTypeId;
  }

  public void setVehicleTypeId(Integer vehicleTypeId) {
    this.vehicleTypeId = vehicleTypeId;
  }

  public Ad vehicleType(String vehicleType) {
    this.vehicleType = vehicleType;
    return this;
  }

   /**
   * Get vehicleType
   * @return vehicleType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVehicleType() {
    return vehicleType;
  }

  public void setVehicleType(String vehicleType) {
    this.vehicleType = vehicleType;
  }

  public Ad makeId(Integer makeId) {
    this.makeId = makeId;
    return this;
  }

   /**
   * Get makeId
   * @return makeId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getMakeId() {
    return makeId;
  }

  public void setMakeId(Integer makeId) {
    this.makeId = makeId;
  }

  public Ad make(String make) {
    this.make = make;
    return this;
  }

   /**
   * Get make
   * @return make
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMake() {
    return make;
  }

  public void setMake(String make) {
    this.make = make;
  }

  public Ad modelId(Integer modelId) {
    this.modelId = modelId;
    return this;
  }

   /**
   * Get modelId
   * @return modelId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getModelId() {
    return modelId;
  }

  public void setModelId(Integer modelId) {
    this.modelId = modelId;
  }

  public Ad model(String model) {
    this.model = model;
    return this;
  }

   /**
   * Get model
   * @return model
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getModel() {
    return model;
  }

  public void setModel(String model) {
    this.model = model;
  }

  public Ad typeName(String typeName) {
    this.typeName = typeName;
    return this;
  }

   /**
   * Get typeName
   * @return typeName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTypeName() {
    return typeName;
  }

  public void setTypeName(String typeName) {
    this.typeName = typeName;
  }

  public Ad typeNameFull(String typeNameFull) {
    this.typeNameFull = typeNameFull;
    return this;
  }

   /**
   * Get typeNameFull
   * @return typeNameFull
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTypeNameFull() {
    return typeNameFull;
  }

  public void setTypeNameFull(String typeNameFull) {
    this.typeNameFull = typeNameFull;
  }

  public Ad dateLastInspection(DateTime dateLastInspection) {
    this.dateLastInspection = dateLastInspection;
    return this;
  }

   /**
   * Get dateLastInspection
   * @return dateLastInspection
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getDateLastInspection() {
    return dateLastInspection;
  }

  public void setDateLastInspection(DateTime dateLastInspection) {
    this.dateLastInspection = dateLastInspection;
  }

  public Ad firstRegYear(Integer firstRegYear) {
    this.firstRegYear = firstRegYear;
    return this;
  }

   /**
   * Get firstRegYear
   * @return firstRegYear
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getFirstRegYear() {
    return firstRegYear;
  }

  public void setFirstRegYear(Integer firstRegYear) {
    this.firstRegYear = firstRegYear;
  }

  public Ad firstRegMonth(Integer firstRegMonth) {
    this.firstRegMonth = firstRegMonth;
    return this;
  }

   /**
   * Get firstRegMonth
   * @return firstRegMonth
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getFirstRegMonth() {
    return firstRegMonth;
  }

  public void setFirstRegMonth(Integer firstRegMonth) {
    this.firstRegMonth = firstRegMonth;
  }

  public Ad modelYear(Integer modelYear) {
    this.modelYear = modelYear;
    return this;
  }

   /**
   * Get modelYear
   * @return modelYear
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getModelYear() {
    return modelYear;
  }

  public void setModelYear(Integer modelYear) {
    this.modelYear = modelYear;
  }

  public Ad modelMonth(Integer modelMonth) {
    this.modelMonth = modelMonth;
    return this;
  }

   /**
   * Get modelMonth
   * @return modelMonth
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getModelMonth() {
    return modelMonth;
  }

  public void setModelMonth(Integer modelMonth) {
    this.modelMonth = modelMonth;
  }

  public Ad conditionTypeId(Integer conditionTypeId) {
    this.conditionTypeId = conditionTypeId;
    return this;
  }

   /**
   * Get conditionTypeId
   * @return conditionTypeId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getConditionTypeId() {
    return conditionTypeId;
  }

  public void setConditionTypeId(Integer conditionTypeId) {
    this.conditionTypeId = conditionTypeId;
  }

  public Ad conditionType(String conditionType) {
    this.conditionType = conditionType;
    return this;
  }

   /**
   * Get conditionType
   * @return conditionType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getConditionType() {
    return conditionType;
  }

  public void setConditionType(String conditionType) {
    this.conditionType = conditionType;
  }

  public Ad bodyTypeId(Integer bodyTypeId) {
    this.bodyTypeId = bodyTypeId;
    return this;
  }

   /**
   * Get bodyTypeId
   * @return bodyTypeId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getBodyTypeId() {
    return bodyTypeId;
  }

  public void setBodyTypeId(Integer bodyTypeId) {
    this.bodyTypeId = bodyTypeId;
  }

  public Ad bodyType(String bodyType) {
    this.bodyType = bodyType;
    return this;
  }

   /**
   * Get bodyType
   * @return bodyType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBodyType() {
    return bodyType;
  }

  public void setBodyType(String bodyType) {
    this.bodyType = bodyType;
  }

  public Ad segmentationTypeId(Integer segmentationTypeId) {
    this.segmentationTypeId = segmentationTypeId;
    return this;
  }

   /**
   * Get segmentationTypeId
   * @return segmentationTypeId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getSegmentationTypeId() {
    return segmentationTypeId;
  }

  public void setSegmentationTypeId(Integer segmentationTypeId) {
    this.segmentationTypeId = segmentationTypeId;
  }

  public Ad segmentationType(String segmentationType) {
    this.segmentationType = segmentationType;
    return this;
  }

   /**
   * Get segmentationType
   * @return segmentationType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSegmentationType() {
    return segmentationType;
  }

  public void setSegmentationType(String segmentationType) {
    this.segmentationType = segmentationType;
  }

  public Ad fuelTypeId(Integer fuelTypeId) {
    this.fuelTypeId = fuelTypeId;
    return this;
  }

   /**
   * Get fuelTypeId
   * @return fuelTypeId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getFuelTypeId() {
    return fuelTypeId;
  }

  public void setFuelTypeId(Integer fuelTypeId) {
    this.fuelTypeId = fuelTypeId;
  }

  public Ad fuelType(String fuelType) {
    this.fuelType = fuelType;
    return this;
  }

   /**
   * Get fuelType
   * @return fuelType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFuelType() {
    return fuelType;
  }

  public void setFuelType(String fuelType) {
    this.fuelType = fuelType;
  }

  public Ad transmissionTypeId(Integer transmissionTypeId) {
    this.transmissionTypeId = transmissionTypeId;
    return this;
  }

   /**
   * Get transmissionTypeId
   * @return transmissionTypeId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getTransmissionTypeId() {
    return transmissionTypeId;
  }

  public void setTransmissionTypeId(Integer transmissionTypeId) {
    this.transmissionTypeId = transmissionTypeId;
  }

  public Ad transmissionType(String transmissionType) {
    this.transmissionType = transmissionType;
    return this;
  }

   /**
   * Get transmissionType
   * @return transmissionType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTransmissionType() {
    return transmissionType;
  }

  public void setTransmissionType(String transmissionType) {
    this.transmissionType = transmissionType;
  }

  public Ad transmissionShaftId(Integer transmissionShaftId) {
    this.transmissionShaftId = transmissionShaftId;
    return this;
  }

   /**
   * Get transmissionShaftId
   * @return transmissionShaftId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getTransmissionShaftId() {
    return transmissionShaftId;
  }

  public void setTransmissionShaftId(Integer transmissionShaftId) {
    this.transmissionShaftId = transmissionShaftId;
  }

  public Ad transmissionShaftType(String transmissionShaftType) {
    this.transmissionShaftType = transmissionShaftType;
    return this;
  }

   /**
   * Get transmissionShaftType
   * @return transmissionShaftType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTransmissionShaftType() {
    return transmissionShaftType;
  }

  public void setTransmissionShaftType(String transmissionShaftType) {
    this.transmissionShaftType = transmissionShaftType;
  }

  public Ad driveTypeId(Integer driveTypeId) {
    this.driveTypeId = driveTypeId;
    return this;
  }

   /**
   * Get driveTypeId
   * @return driveTypeId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getDriveTypeId() {
    return driveTypeId;
  }

  public void setDriveTypeId(Integer driveTypeId) {
    this.driveTypeId = driveTypeId;
  }

  public Ad driveType(String driveType) {
    this.driveType = driveType;
    return this;
  }

   /**
   * Get driveType
   * @return driveType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDriveType() {
    return driveType;
  }

  public void setDriveType(String driveType) {
    this.driveType = driveType;
  }

  public Ad pollutionNormTypeId(Integer pollutionNormTypeId) {
    this.pollutionNormTypeId = pollutionNormTypeId;
    return this;
  }

   /**
   * Get pollutionNormTypeId
   * @return pollutionNormTypeId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getPollutionNormTypeId() {
    return pollutionNormTypeId;
  }

  public void setPollutionNormTypeId(Integer pollutionNormTypeId) {
    this.pollutionNormTypeId = pollutionNormTypeId;
  }

  public Ad pollutionNormType(String pollutionNormType) {
    this.pollutionNormType = pollutionNormType;
    return this;
  }

   /**
   * Get pollutionNormType
   * @return pollutionNormType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPollutionNormType() {
    return pollutionNormType;
  }

  public void setPollutionNormType(String pollutionNormType) {
    this.pollutionNormType = pollutionNormType;
  }

  public Ad licenseCategoryTypeId(Integer licenseCategoryTypeId) {
    this.licenseCategoryTypeId = licenseCategoryTypeId;
    return this;
  }

   /**
   * Get licenseCategoryTypeId
   * @return licenseCategoryTypeId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getLicenseCategoryTypeId() {
    return licenseCategoryTypeId;
  }

  public void setLicenseCategoryTypeId(Integer licenseCategoryTypeId) {
    this.licenseCategoryTypeId = licenseCategoryTypeId;
  }

  public Ad licenseCategoryType(String licenseCategoryType) {
    this.licenseCategoryType = licenseCategoryType;
    return this;
  }

   /**
   * Get licenseCategoryType
   * @return licenseCategoryType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLicenseCategoryType() {
    return licenseCategoryType;
  }

  public void setLicenseCategoryType(String licenseCategoryType) {
    this.licenseCategoryType = licenseCategoryType;
  }

  public Ad consumptionRatingTypeId(Integer consumptionRatingTypeId) {
    this.consumptionRatingTypeId = consumptionRatingTypeId;
    return this;
  }

   /**
   * Get consumptionRatingTypeId
   * @return consumptionRatingTypeId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getConsumptionRatingTypeId() {
    return consumptionRatingTypeId;
  }

  public void setConsumptionRatingTypeId(Integer consumptionRatingTypeId) {
    this.consumptionRatingTypeId = consumptionRatingTypeId;
  }

  public Ad consumptionRatingType(String consumptionRatingType) {
    this.consumptionRatingType = consumptionRatingType;
    return this;
  }

   /**
   * Get consumptionRatingType
   * @return consumptionRatingType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getConsumptionRatingType() {
    return consumptionRatingType;
  }

  public void setConsumptionRatingType(String consumptionRatingType) {
    this.consumptionRatingType = consumptionRatingType;
  }

  public Ad cylinderDesignTypeId(Integer cylinderDesignTypeId) {
    this.cylinderDesignTypeId = cylinderDesignTypeId;
    return this;
  }

   /**
   * Get cylinderDesignTypeId
   * @return cylinderDesignTypeId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getCylinderDesignTypeId() {
    return cylinderDesignTypeId;
  }

  public void setCylinderDesignTypeId(Integer cylinderDesignTypeId) {
    this.cylinderDesignTypeId = cylinderDesignTypeId;
  }

  public Ad cylinderDesignType(String cylinderDesignType) {
    this.cylinderDesignType = cylinderDesignType;
    return this;
  }

   /**
   * Get cylinderDesignType
   * @return cylinderDesignType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCylinderDesignType() {
    return cylinderDesignType;
  }

  public void setCylinderDesignType(String cylinderDesignType) {
    this.cylinderDesignType = cylinderDesignType;
  }

  public Ad bodyColorId(Integer bodyColorId) {
    this.bodyColorId = bodyColorId;
    return this;
  }

   /**
   * Get bodyColorId
   * @return bodyColorId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getBodyColorId() {
    return bodyColorId;
  }

  public void setBodyColorId(Integer bodyColorId) {
    this.bodyColorId = bodyColorId;
  }

  public Ad bodyColor(String bodyColor) {
    this.bodyColor = bodyColor;
    return this;
  }

   /**
   * Get bodyColor
   * @return bodyColor
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBodyColor() {
    return bodyColor;
  }

  public void setBodyColor(String bodyColor) {
    this.bodyColor = bodyColor;
  }

  public Ad interiorColorId(Integer interiorColorId) {
    this.interiorColorId = interiorColorId;
    return this;
  }

   /**
   * Get interiorColorId
   * @return interiorColorId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getInteriorColorId() {
    return interiorColorId;
  }

  public void setInteriorColorId(Integer interiorColorId) {
    this.interiorColorId = interiorColorId;
  }

  public Ad interiorColor(String interiorColor) {
    this.interiorColor = interiorColor;
    return this;
  }

   /**
   * Get interiorColor
   * @return interiorColor
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getInteriorColor() {
    return interiorColor;
  }

  public void setInteriorColor(String interiorColor) {
    this.interiorColor = interiorColor;
  }

  public Ad price(Double price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getPrice() {
    return price;
  }

  public void setPrice(Double price) {
    this.price = price;
  }

  public Ad priceNew(Double priceNew) {
    this.priceNew = priceNew;
    return this;
  }

   /**
   * Get priceNew
   * @return priceNew
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getPriceNew() {
    return priceNew;
  }

  public void setPriceNew(Double priceNew) {
    this.priceNew = priceNew;
  }

  public Ad priceOriginal(Double priceOriginal) {
    this.priceOriginal = priceOriginal;
    return this;
  }

   /**
   * Get priceOriginal
   * @return priceOriginal
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getPriceOriginal() {
    return priceOriginal;
  }

  public void setPriceOriginal(Double priceOriginal) {
    this.priceOriginal = priceOriginal;
  }

  public Ad km(Integer km) {
    this.km = km;
    return this;
  }

   /**
   * Get km
   * @return km
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getKm() {
    return km;
  }

  public void setKm(Integer km) {
    this.km = km;
  }

  public Ad consumptionCity(Double consumptionCity) {
    this.consumptionCity = consumptionCity;
    return this;
  }

   /**
   * Get consumptionCity
   * @return consumptionCity
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getConsumptionCity() {
    return consumptionCity;
  }

  public void setConsumptionCity(Double consumptionCity) {
    this.consumptionCity = consumptionCity;
  }

  public Ad consumptionLand(Double consumptionLand) {
    this.consumptionLand = consumptionLand;
    return this;
  }

   /**
   * Get consumptionLand
   * @return consumptionLand
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getConsumptionLand() {
    return consumptionLand;
  }

  public void setConsumptionLand(Double consumptionLand) {
    this.consumptionLand = consumptionLand;
  }

  public Ad consumptionTotal(Double consumptionTotal) {
    this.consumptionTotal = consumptionTotal;
    return this;
  }

   /**
   * Get consumptionTotal
   * @return consumptionTotal
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getConsumptionTotal() {
    return consumptionTotal;
  }

  public void setConsumptionTotal(Double consumptionTotal) {
    this.consumptionTotal = consumptionTotal;
  }

  public Ad consumptionGasCity(Double consumptionGasCity) {
    this.consumptionGasCity = consumptionGasCity;
    return this;
  }

   /**
   * Get consumptionGasCity
   * @return consumptionGasCity
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getConsumptionGasCity() {
    return consumptionGasCity;
  }

  public void setConsumptionGasCity(Double consumptionGasCity) {
    this.consumptionGasCity = consumptionGasCity;
  }

  public Ad consumptionGasLand(Double consumptionGasLand) {
    this.consumptionGasLand = consumptionGasLand;
    return this;
  }

   /**
   * Get consumptionGasLand
   * @return consumptionGasLand
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getConsumptionGasLand() {
    return consumptionGasLand;
  }

  public void setConsumptionGasLand(Double consumptionGasLand) {
    this.consumptionGasLand = consumptionGasLand;
  }

  public Ad consumptionGasTotal(Double consumptionGasTotal) {
    this.consumptionGasTotal = consumptionGasTotal;
    return this;
  }

   /**
   * Get consumptionGasTotal
   * @return consumptionGasTotal
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getConsumptionGasTotal() {
    return consumptionGasTotal;
  }

  public void setConsumptionGasTotal(Double consumptionGasTotal) {
    this.consumptionGasTotal = consumptionGasTotal;
  }

  public Ad consumptionPower(Double consumptionPower) {
    this.consumptionPower = consumptionPower;
    return this;
  }

   /**
   * Get consumptionPower
   * @return consumptionPower
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getConsumptionPower() {
    return consumptionPower;
  }

  public void setConsumptionPower(Double consumptionPower) {
    this.consumptionPower = consumptionPower;
  }

  public Ad petrolEquivalent(Double petrolEquivalent) {
    this.petrolEquivalent = petrolEquivalent;
    return this;
  }

   /**
   * Get petrolEquivalent
   * @return petrolEquivalent
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getPetrolEquivalent() {
    return petrolEquivalent;
  }

  public void setPetrolEquivalent(Double petrolEquivalent) {
    this.petrolEquivalent = petrolEquivalent;
  }

  public Ad co2Emission(Integer co2Emission) {
    this.co2Emission = co2Emission;
    return this;
  }

   /**
   * Get co2Emission
   * @return co2Emission
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getCo2Emission() {
    return co2Emission;
  }

  public void setCo2Emission(Integer co2Emission) {
    this.co2Emission = co2Emission;
  }

  public Ad co2EmissionAverage(Integer co2EmissionAverage) {
    this.co2EmissionAverage = co2EmissionAverage;
    return this;
  }

   /**
   * Get co2EmissionAverage
   * @return co2EmissionAverage
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getCo2EmissionAverage() {
    return co2EmissionAverage;
  }

  public void setCo2EmissionAverage(Integer co2EmissionAverage) {
    this.co2EmissionAverage = co2EmissionAverage;
  }

  public Ad co2EmissionPowerProduction(Double co2EmissionPowerProduction) {
    this.co2EmissionPowerProduction = co2EmissionPowerProduction;
    return this;
  }

   /**
   * Get co2EmissionPowerProduction
   * @return co2EmissionPowerProduction
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getCo2EmissionPowerProduction() {
    return co2EmissionPowerProduction;
  }

  public void setCo2EmissionPowerProduction(Double co2EmissionPowerProduction) {
    this.co2EmissionPowerProduction = co2EmissionPowerProduction;
  }

  public Ad doors(Integer doors) {
    this.doors = doors;
    return this;
  }

   /**
   * Get doors
   * @return doors
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getDoors() {
    return doors;
  }

  public void setDoors(Integer doors) {
    this.doors = doors;
  }

  public Ad seats(Integer seats) {
    this.seats = seats;
    return this;
  }

   /**
   * Get seats
   * @return seats
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getSeats() {
    return seats;
  }

  public void setSeats(Integer seats) {
    this.seats = seats;
  }

  public Ad cylinders(Integer cylinders) {
    this.cylinders = cylinders;
    return this;
  }

   /**
   * Get cylinders
   * @return cylinders
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getCylinders() {
    return cylinders;
  }

  public void setCylinders(Integer cylinders) {
    this.cylinders = cylinders;
  }

  public Ad gears(Integer gears) {
    this.gears = gears;
    return this;
  }

   /**
   * Get gears
   * @return gears
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getGears() {
    return gears;
  }

  public void setGears(Integer gears) {
    this.gears = gears;
  }

  public Ad ccm(Integer ccm) {
    this.ccm = ccm;
    return this;
  }

   /**
   * Get ccm
   * @return ccm
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getCcm() {
    return ccm;
  }

  public void setCcm(Integer ccm) {
    this.ccm = ccm;
  }

  public Ad hp(Double hp) {
    this.hp = hp;
    return this;
  }

   /**
   * Get hp
   * @return hp
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getHp() {
    return hp;
  }

  public void setHp(Double hp) {
    this.hp = hp;
  }

  public Ad kw(Double kw) {
    this.kw = kw;
    return this;
  }

   /**
   * Get kw
   * @return kw
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getKw() {
    return kw;
  }

  public void setKw(Double kw) {
    this.kw = kw;
  }

  public Ad weightKerb(Integer weightKerb) {
    this.weightKerb = weightKerb;
    return this;
  }

   /**
   * Get weightKerb
   * @return weightKerb
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getWeightKerb() {
    return weightKerb;
  }

  public void setWeightKerb(Integer weightKerb) {
    this.weightKerb = weightKerb;
  }

  public Ad weightTotal(Integer weightTotal) {
    this.weightTotal = weightTotal;
    return this;
  }

   /**
   * Get weightTotal
   * @return weightTotal
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getWeightTotal() {
    return weightTotal;
  }

  public void setWeightTotal(Integer weightTotal) {
    this.weightTotal = weightTotal;
  }

  public Ad trailerLoadBreaked(Integer trailerLoadBreaked) {
    this.trailerLoadBreaked = trailerLoadBreaked;
    return this;
  }

   /**
   * Get trailerLoadBreaked
   * @return trailerLoadBreaked
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getTrailerLoadBreaked() {
    return trailerLoadBreaked;
  }

  public void setTrailerLoadBreaked(Integer trailerLoadBreaked) {
    this.trailerLoadBreaked = trailerLoadBreaked;
  }

  public Ad length(Integer length) {
    this.length = length;
    return this;
  }

   /**
   * Get length
   * @return length
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getLength() {
    return length;
  }

  public void setLength(Integer length) {
    this.length = length;
  }

  public Ad width(Integer width) {
    this.width = width;
    return this;
  }

   /**
   * Get width
   * @return width
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getWidth() {
    return width;
  }

  public void setWidth(Integer width) {
    this.width = width;
  }

  public Ad height(Integer height) {
    this.height = height;
    return this;
  }

   /**
   * Get height
   * @return height
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getHeight() {
    return height;
  }

  public void setHeight(Integer height) {
    this.height = height;
  }

  public Ad bootHeight(Integer bootHeight) {
    this.bootHeight = bootHeight;
    return this;
  }

   /**
   * Get bootHeight
   * @return bootHeight
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getBootHeight() {
    return bootHeight;
  }

  public void setBootHeight(Integer bootHeight) {
    this.bootHeight = bootHeight;
  }

  public Ad bootWidth(Integer bootWidth) {
    this.bootWidth = bootWidth;
    return this;
  }

   /**
   * Get bootWidth
   * @return bootWidth
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getBootWidth() {
    return bootWidth;
  }

  public void setBootWidth(Integer bootWidth) {
    this.bootWidth = bootWidth;
  }

  public Ad bootLength(Integer bootLength) {
    this.bootLength = bootLength;
    return this;
  }

   /**
   * Get bootLength
   * @return bootLength
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getBootLength() {
    return bootLength;
  }

  public void setBootLength(Integer bootLength) {
    this.bootLength = bootLength;
  }

  public Ad bootVolume(Integer bootVolume) {
    this.bootVolume = bootVolume;
    return this;
  }

   /**
   * Get bootVolume
   * @return bootVolume
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getBootVolume() {
    return bootVolume;
  }

  public void setBootVolume(Integer bootVolume) {
    this.bootVolume = bootVolume;
  }

  public Ad payLoad(Integer payLoad) {
    this.payLoad = payLoad;
    return this;
  }

   /**
   * Get payLoad
   * @return payLoad
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getPayLoad() {
    return payLoad;
  }

  public void setPayLoad(Integer payLoad) {
    this.payLoad = payLoad;
  }

  public Ad wheelbase(Integer wheelbase) {
    this.wheelbase = wheelbase;
    return this;
  }

   /**
   * Get wheelbase
   * @return wheelbase
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getWheelbase() {
    return wheelbase;
  }

  public void setWheelbase(Integer wheelbase) {
    this.wheelbase = wheelbase;
  }

  public Ad axis(Integer axis) {
    this.axis = axis;
    return this;
  }

   /**
   * Get axis
   * @return axis
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getAxis() {
    return axis;
  }

  public void setAxis(Integer axis) {
    this.axis = axis;
  }

  public Ad sleepingBerths(Integer sleepingBerths) {
    this.sleepingBerths = sleepingBerths;
    return this;
  }

   /**
   * Get sleepingBerths
   * @return sleepingBerths
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getSleepingBerths() {
    return sleepingBerths;
  }

  public void setSleepingBerths(Integer sleepingBerths) {
    this.sleepingBerths = sleepingBerths;
  }

  public Ad isBodyColorMetallic(Boolean isBodyColorMetallic) {
    this.isBodyColorMetallic = isBodyColorMetallic;
    return this;
  }

   /**
   * Get isBodyColorMetallic
   * @return isBodyColorMetallic
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsBodyColorMetallic() {
    return isBodyColorMetallic;
  }

  public void setIsBodyColorMetallic(Boolean isBodyColorMetallic) {
    this.isBodyColorMetallic = isBodyColorMetallic;
  }

  public Ad bitwiseEquipments(Long bitwiseEquipments) {
    this.bitwiseEquipments = bitwiseEquipments;
    return this;
  }

   /**
   * Get bitwiseEquipments
   * @return bitwiseEquipments
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getBitwiseEquipments() {
    return bitwiseEquipments;
  }

  public void setBitwiseEquipments(Long bitwiseEquipments) {
    this.bitwiseEquipments = bitwiseEquipments;
  }

  public Ad originalTextBodyColor(String originalTextBodyColor) {
    this.originalTextBodyColor = originalTextBodyColor;
    return this;
  }

   /**
   * Get originalTextBodyColor
   * @return originalTextBodyColor
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOriginalTextBodyColor() {
    return originalTextBodyColor;
  }

  public void setOriginalTextBodyColor(String originalTextBodyColor) {
    this.originalTextBodyColor = originalTextBodyColor;
  }

  public Ad originalTextInteriorColor(String originalTextInteriorColor) {
    this.originalTextInteriorColor = originalTextInteriorColor;
    return this;
  }

   /**
   * Get originalTextInteriorColor
   * @return originalTextInteriorColor
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOriginalTextInteriorColor() {
    return originalTextInteriorColor;
  }

  public void setOriginalTextInteriorColor(String originalTextInteriorColor) {
    this.originalTextInteriorColor = originalTextInteriorColor;
  }

  public Ad originalTextLanguage(String originalTextLanguage) {
    this.originalTextLanguage = originalTextLanguage;
    return this;
  }

   /**
   * Get originalTextLanguage
   * @return originalTextLanguage
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOriginalTextLanguage() {
    return originalTextLanguage;
  }

  public void setOriginalTextLanguage(String originalTextLanguage) {
    this.originalTextLanguage = originalTextLanguage;
  }

  public Ad teaser(String teaser) {
    this.teaser = teaser;
    return this;
  }

   /**
   * Get teaser
   * @return teaser
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTeaser() {
    return teaser;
  }

  public void setTeaser(String teaser) {
    this.teaser = teaser;
  }

  public Ad dateNewRelevant(DateTime dateNewRelevant) {
    this.dateNewRelevant = dateNewRelevant;
    return this;
  }

   /**
   * Get dateNewRelevant
   * @return dateNewRelevant
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getDateNewRelevant() {
    return dateNewRelevant;
  }

  public void setDateNewRelevant(DateTime dateNewRelevant) {
    this.dateNewRelevant = dateNewRelevant;
  }

  public Ad isBehaveAsNew(Boolean isBehaveAsNew) {
    this.isBehaveAsNew = isBehaveAsNew;
    return this;
  }

   /**
   * Get isBehaveAsNew
   * @return isBehaveAsNew
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsBehaveAsNew() {
    return isBehaveAsNew;
  }

  public void setIsBehaveAsNew(Boolean isBehaveAsNew) {
    this.isBehaveAsNew = isBehaveAsNew;
  }

  public Ad dateNewFlagExpires(DateTime dateNewFlagExpires) {
    this.dateNewFlagExpires = dateNewFlagExpires;
    return this;
  }

   /**
   * Get dateNewFlagExpires
   * @return dateNewFlagExpires
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getDateNewFlagExpires() {
    return dateNewFlagExpires;
  }

  public void setDateNewFlagExpires(DateTime dateNewFlagExpires) {
    this.dateNewFlagExpires = dateNewFlagExpires;
  }

  public Ad seoDetail(String seoDetail) {
    this.seoDetail = seoDetail;
    return this;
  }

   /**
   * Get seoDetail
   * @return seoDetail
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSeoDetail() {
    return seoDetail;
  }

  public void setSeoDetail(String seoDetail) {
    this.seoDetail = seoDetail;
  }

  public Ad dateTopListing(DateTime dateTopListing) {
    this.dateTopListing = dateTopListing;
    return this;
  }

   /**
   * Get dateTopListing
   * @return dateTopListing
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getDateTopListing() {
    return dateTopListing;
  }

  public void setDateTopListing(DateTime dateTopListing) {
    this.dateTopListing = dateTopListing;
  }

  public Ad insurance(Insurance insurance) {
    this.insurance = insurance;
    return this;
  }

   /**
   * Get insurance
   * @return insurance
  **/
  @ApiModelProperty(example = "null", value = "")
  public Insurance getInsurance() {
    return insurance;
  }

  public void setInsurance(Insurance insurance) {
    this.insurance = insurance;
  }

  public Ad showCashSentinel(Boolean showCashSentinel) {
    this.showCashSentinel = showCashSentinel;
    return this;
  }

   /**
   * Get showCashSentinel
   * @return showCashSentinel
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getShowCashSentinel() {
    return showCashSentinel;
  }

  public void setShowCashSentinel(Boolean showCashSentinel) {
    this.showCashSentinel = showCashSentinel;
  }

  public Ad images(AdImages images) {
    this.images = images;
    return this;
  }

   /**
   * Get images
   * @return images
  **/
  @ApiModelProperty(example = "null", value = "")
  public AdImages getImages() {
    return images;
  }

  public void setImages(AdImages images) {
    this.images = images;
  }

  public Ad documents(List<AdDocument> documents) {
    this.documents = documents;
    return this;
  }

  public Ad addDocumentsItem(AdDocument documentsItem) {
    this.documents.add(documentsItem);
    return this;
  }

   /**
   * Get documents
   * @return documents
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<AdDocument> getDocuments() {
    return documents;
  }

  public void setDocuments(List<AdDocument> documents) {
    this.documents = documents;
  }

  public Ad videos(List<AdVideo> videos) {
    this.videos = videos;
    return this;
  }

  public Ad addVideosItem(AdVideo videosItem) {
    this.videos.add(videosItem);
    return this;
  }

   /**
   * Get videos
   * @return videos
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<AdVideo> getVideos() {
    return videos;
  }

  public void setVideos(List<AdVideo> videos) {
    this.videos = videos;
  }

  public Ad logoId(Integer logoId) {
    this.logoId = logoId;
    return this;
  }

   /**
   * Get logoId
   * @return logoId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getLogoId() {
    return logoId;
  }

  public void setLogoId(Integer logoId) {
    this.logoId = logoId;
  }

  public Ad logoText(String logoText) {
    this.logoText = logoText;
    return this;
  }

   /**
   * Get logoText
   * @return logoText
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLogoText() {
    return logoText;
  }

  public void setLogoText(String logoText) {
    this.logoText = logoText;
  }

  public Ad logoUrl(String logoUrl) {
    this.logoUrl = logoUrl;
    return this;
  }

   /**
   * Get logoUrl
   * @return logoUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLogoUrl() {
    return logoUrl;
  }

  public void setLogoUrl(String logoUrl) {
    this.logoUrl = logoUrl;
  }

  public Ad logoImageUrl(String logoImageUrl) {
    this.logoImageUrl = logoImageUrl;
    return this;
  }

   /**
   * Get logoImageUrl
   * @return logoImageUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLogoImageUrl() {
    return logoImageUrl;
  }

  public void setLogoImageUrl(String logoImageUrl) {
    this.logoImageUrl = logoImageUrl;
  }

  public Ad logoTrackingUrl(String logoTrackingUrl) {
    this.logoTrackingUrl = logoTrackingUrl;
    return this;
  }

   /**
   * Get logoTrackingUrl
   * @return logoTrackingUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLogoTrackingUrl() {
    return logoTrackingUrl;
  }

  public void setLogoTrackingUrl(String logoTrackingUrl) {
    this.logoTrackingUrl = logoTrackingUrl;
  }

  public Ad isAccidentVehicle(Boolean isAccidentVehicle) {
    this.isAccidentVehicle = isAccidentVehicle;
    return this;
  }

   /**
   * Get isAccidentVehicle
   * @return isAccidentVehicle
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsAccidentVehicle() {
    return isAccidentVehicle;
  }

  public void setIsAccidentVehicle(Boolean isAccidentVehicle) {
    this.isAccidentVehicle = isAccidentVehicle;
  }

  public Ad isExchangeable(Boolean isExchangeable) {
    this.isExchangeable = isExchangeable;
    return this;
  }

   /**
   * Get isExchangeable
   * @return isExchangeable
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsExchangeable() {
    return isExchangeable;
  }

  public void setIsExchangeable(Boolean isExchangeable) {
    this.isExchangeable = isExchangeable;
  }

  public Ad isExport(Boolean isExport) {
    this.isExport = isExport;
    return this;
  }

   /**
   * Get isExport
   * @return isExport
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsExport() {
    return isExport;
  }

  public void setIsExport(Boolean isExport) {
    this.isExport = isExport;
  }

  public Ad isHandicapConverted(Boolean isHandicapConverted) {
    this.isHandicapConverted = isHandicapConverted;
    return this;
  }

   /**
   * Get isHandicapConverted
   * @return isHandicapConverted
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsHandicapConverted() {
    return isHandicapConverted;
  }

  public void setIsHandicapConverted(Boolean isHandicapConverted) {
    this.isHandicapConverted = isHandicapConverted;
  }

  public Ad isInspected(Boolean isInspected) {
    this.isInspected = isInspected;
    return this;
  }

   /**
   * Get isInspected
   * @return isInspected
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsInspected() {
    return isInspected;
  }

  public void setIsInspected(Boolean isInspected) {
    this.isInspected = isInspected;
  }

  public Ad isDirectImport(Boolean isDirectImport) {
    this.isDirectImport = isDirectImport;
    return this;
  }

   /**
   * Get isDirectImport
   * @return isDirectImport
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsDirectImport() {
    return isDirectImport;
  }

  public void setIsDirectImport(Boolean isDirectImport) {
    this.isDirectImport = isDirectImport;
  }

  public Ad isLocationExact(Boolean isLocationExact) {
    this.isLocationExact = isLocationExact;
    return this;
  }

   /**
   * Get isLocationExact
   * @return isLocationExact
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsLocationExact() {
    return isLocationExact;
  }

  public void setIsLocationExact(Boolean isLocationExact) {
    this.isLocationExact = isLocationExact;
  }

  public Ad isLeasable(Boolean isLeasable) {
    this.isLeasable = isLeasable;
    return this;
  }

   /**
   * Get isLeasable
   * @return isLeasable
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsLeasable() {
    return isLeasable;
  }

  public void setIsLeasable(Boolean isLeasable) {
    this.isLeasable = isLeasable;
  }

  public Ad isRacingVehicle(Boolean isRacingVehicle) {
    this.isRacingVehicle = isRacingVehicle;
    return this;
  }

   /**
   * Get isRacingVehicle
   * @return isRacingVehicle
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsRacingVehicle() {
    return isRacingVehicle;
  }

  public void setIsRacingVehicle(Boolean isRacingVehicle) {
    this.isRacingVehicle = isRacingVehicle;
  }

  public Ad isThrottleKitAvailable(Boolean isThrottleKitAvailable) {
    this.isThrottleKitAvailable = isThrottleKitAvailable;
    return this;
  }

   /**
   * Get isThrottleKitAvailable
   * @return isThrottleKitAvailable
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsThrottleKitAvailable() {
    return isThrottleKitAvailable;
  }

  public void setIsThrottleKitAvailable(Boolean isThrottleKitAvailable) {
    this.isThrottleKitAvailable = isThrottleKitAvailable;
  }

  public Ad isThrottleKitPossible(Boolean isThrottleKitPossible) {
    this.isThrottleKitPossible = isThrottleKitPossible;
    return this;
  }

   /**
   * Get isThrottleKitPossible
   * @return isThrottleKitPossible
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsThrottleKitPossible() {
    return isThrottleKitPossible;
  }

  public void setIsThrottleKitPossible(Boolean isThrottleKitPossible) {
    this.isThrottleKitPossible = isThrottleKitPossible;
  }

  public Ad isTuned(Boolean isTuned) {
    this.isTuned = isTuned;
    return this;
  }

   /**
   * Get isTuned
   * @return isTuned
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsTuned() {
    return isTuned;
  }

  public void setIsTuned(Boolean isTuned) {
    this.isTuned = isTuned;
  }

  public Ad equipment(AdEquipment equipment) {
    this.equipment = equipment;
    return this;
  }

   /**
   * Get equipment
   * @return equipment
  **/
  @ApiModelProperty(example = "null", value = "")
  public AdEquipment getEquipment() {
    return equipment;
  }

  public void setEquipment(AdEquipment equipment) {
    this.equipment = equipment;
  }

  public Ad longitude(Double longitude) {
    this.longitude = longitude;
    return this;
  }

   /**
   * Get longitude
   * @return longitude
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getLongitude() {
    return longitude;
  }

  public void setLongitude(Double longitude) {
    this.longitude = longitude;
  }

  public Ad latitude(Double latitude) {
    this.latitude = latitude;
    return this;
  }

   /**
   * Get latitude
   * @return latitude
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getLatitude() {
    return latitude;
  }

  public void setLatitude(Double latitude) {
    this.latitude = latitude;
  }

  public Ad comments(String comments) {
    this.comments = comments;
    return this;
  }

   /**
   * Get comments
   * @return comments
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getComments() {
    return comments;
  }

  public void setComments(String comments) {
    this.comments = comments;
  }

  public Ad internalComments(String internalComments) {
    this.internalComments = internalComments;
    return this;
  }

   /**
   * Get internalComments
   * @return internalComments
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getInternalComments() {
    return internalComments;
  }

  public void setInternalComments(String internalComments) {
    this.internalComments = internalComments;
  }

  public Ad hasWarranty(Boolean hasWarranty) {
    this.hasWarranty = hasWarranty;
    return this;
  }

   /**
   * Get hasWarranty
   * @return hasWarranty
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getHasWarranty() {
    return hasWarranty;
  }

  public void setHasWarranty(Boolean hasWarranty) {
    this.hasWarranty = hasWarranty;
  }

  public Ad warrantyInMonths(Integer warrantyInMonths) {
    this.warrantyInMonths = warrantyInMonths;
    return this;
  }

   /**
   * Get warrantyInMonths
   * @return warrantyInMonths
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getWarrantyInMonths() {
    return warrantyInMonths;
  }

  public void setWarrantyInMonths(Integer warrantyInMonths) {
    this.warrantyInMonths = warrantyInMonths;
  }

  public Ad warrantyDescription(String warrantyDescription) {
    this.warrantyDescription = warrantyDescription;
    return this;
  }

   /**
   * Get warrantyDescription
   * @return warrantyDescription
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getWarrantyDescription() {
    return warrantyDescription;
  }

  public void setWarrantyDescription(String warrantyDescription) {
    this.warrantyDescription = warrantyDescription;
  }

  public Ad isHighlighted(Boolean isHighlighted) {
    this.isHighlighted = isHighlighted;
    return this;
  }

   /**
   * Get isHighlighted
   * @return isHighlighted
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsHighlighted() {
    return isHighlighted;
  }

  public void setIsHighlighted(Boolean isHighlighted) {
    this.isHighlighted = isHighlighted;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Ad ad = (Ad) o;
    return Objects.equals(this.id, ad.id) &&
        Objects.equals(this.certificationCode, ad.certificationCode) &&
        Objects.equals(this.chassisCode, ad.chassisCode) &&
        Objects.equals(this.customerVehicleCode, ad.customerVehicleCode) &&
        Objects.equals(this.userId, ad.userId) &&
        Objects.equals(this.userTypeId, ad.userTypeId) &&
        Objects.equals(this.accountId, ad.accountId) &&
        Objects.equals(this.addressId, ad.addressId) &&
        Objects.equals(this.seller, ad.seller) &&
        Objects.equals(this.status, ad.status) &&
        Objects.equals(this.dateCreated, ad.dateCreated) &&
        Objects.equals(this.dateModified, ad.dateModified) &&
        Objects.equals(this.dateValidFrom, ad.dateValidFrom) &&
        Objects.equals(this.dateValidTo, ad.dateValidTo) &&
        Objects.equals(this.isOnline, ad.isOnline) &&
        Objects.equals(this.vehicleVisibilityId, ad.vehicleVisibilityId) &&
        Objects.equals(this.vehicleTypeGroupId, ad.vehicleTypeGroupId) &&
        Objects.equals(this.vehicleTypeId, ad.vehicleTypeId) &&
        Objects.equals(this.vehicleType, ad.vehicleType) &&
        Objects.equals(this.makeId, ad.makeId) &&
        Objects.equals(this.make, ad.make) &&
        Objects.equals(this.modelId, ad.modelId) &&
        Objects.equals(this.model, ad.model) &&
        Objects.equals(this.typeName, ad.typeName) &&
        Objects.equals(this.typeNameFull, ad.typeNameFull) &&
        Objects.equals(this.dateLastInspection, ad.dateLastInspection) &&
        Objects.equals(this.firstRegYear, ad.firstRegYear) &&
        Objects.equals(this.firstRegMonth, ad.firstRegMonth) &&
        Objects.equals(this.modelYear, ad.modelYear) &&
        Objects.equals(this.modelMonth, ad.modelMonth) &&
        Objects.equals(this.conditionTypeId, ad.conditionTypeId) &&
        Objects.equals(this.conditionType, ad.conditionType) &&
        Objects.equals(this.bodyTypeId, ad.bodyTypeId) &&
        Objects.equals(this.bodyType, ad.bodyType) &&
        Objects.equals(this.segmentationTypeId, ad.segmentationTypeId) &&
        Objects.equals(this.segmentationType, ad.segmentationType) &&
        Objects.equals(this.fuelTypeId, ad.fuelTypeId) &&
        Objects.equals(this.fuelType, ad.fuelType) &&
        Objects.equals(this.transmissionTypeId, ad.transmissionTypeId) &&
        Objects.equals(this.transmissionType, ad.transmissionType) &&
        Objects.equals(this.transmissionShaftId, ad.transmissionShaftId) &&
        Objects.equals(this.transmissionShaftType, ad.transmissionShaftType) &&
        Objects.equals(this.driveTypeId, ad.driveTypeId) &&
        Objects.equals(this.driveType, ad.driveType) &&
        Objects.equals(this.pollutionNormTypeId, ad.pollutionNormTypeId) &&
        Objects.equals(this.pollutionNormType, ad.pollutionNormType) &&
        Objects.equals(this.licenseCategoryTypeId, ad.licenseCategoryTypeId) &&
        Objects.equals(this.licenseCategoryType, ad.licenseCategoryType) &&
        Objects.equals(this.consumptionRatingTypeId, ad.consumptionRatingTypeId) &&
        Objects.equals(this.consumptionRatingType, ad.consumptionRatingType) &&
        Objects.equals(this.cylinderDesignTypeId, ad.cylinderDesignTypeId) &&
        Objects.equals(this.cylinderDesignType, ad.cylinderDesignType) &&
        Objects.equals(this.bodyColorId, ad.bodyColorId) &&
        Objects.equals(this.bodyColor, ad.bodyColor) &&
        Objects.equals(this.interiorColorId, ad.interiorColorId) &&
        Objects.equals(this.interiorColor, ad.interiorColor) &&
        Objects.equals(this.price, ad.price) &&
        Objects.equals(this.priceNew, ad.priceNew) &&
        Objects.equals(this.priceOriginal, ad.priceOriginal) &&
        Objects.equals(this.km, ad.km) &&
        Objects.equals(this.consumptionCity, ad.consumptionCity) &&
        Objects.equals(this.consumptionLand, ad.consumptionLand) &&
        Objects.equals(this.consumptionTotal, ad.consumptionTotal) &&
        Objects.equals(this.consumptionGasCity, ad.consumptionGasCity) &&
        Objects.equals(this.consumptionGasLand, ad.consumptionGasLand) &&
        Objects.equals(this.consumptionGasTotal, ad.consumptionGasTotal) &&
        Objects.equals(this.consumptionPower, ad.consumptionPower) &&
        Objects.equals(this.petrolEquivalent, ad.petrolEquivalent) &&
        Objects.equals(this.co2Emission, ad.co2Emission) &&
        Objects.equals(this.co2EmissionAverage, ad.co2EmissionAverage) &&
        Objects.equals(this.co2EmissionPowerProduction, ad.co2EmissionPowerProduction) &&
        Objects.equals(this.doors, ad.doors) &&
        Objects.equals(this.seats, ad.seats) &&
        Objects.equals(this.cylinders, ad.cylinders) &&
        Objects.equals(this.gears, ad.gears) &&
        Objects.equals(this.ccm, ad.ccm) &&
        Objects.equals(this.hp, ad.hp) &&
        Objects.equals(this.kw, ad.kw) &&
        Objects.equals(this.weightKerb, ad.weightKerb) &&
        Objects.equals(this.weightTotal, ad.weightTotal) &&
        Objects.equals(this.trailerLoadBreaked, ad.trailerLoadBreaked) &&
        Objects.equals(this.length, ad.length) &&
        Objects.equals(this.width, ad.width) &&
        Objects.equals(this.height, ad.height) &&
        Objects.equals(this.bootHeight, ad.bootHeight) &&
        Objects.equals(this.bootWidth, ad.bootWidth) &&
        Objects.equals(this.bootLength, ad.bootLength) &&
        Objects.equals(this.bootVolume, ad.bootVolume) &&
        Objects.equals(this.payLoad, ad.payLoad) &&
        Objects.equals(this.wheelbase, ad.wheelbase) &&
        Objects.equals(this.axis, ad.axis) &&
        Objects.equals(this.sleepingBerths, ad.sleepingBerths) &&
        Objects.equals(this.isBodyColorMetallic, ad.isBodyColorMetallic) &&
        Objects.equals(this.bitwiseEquipments, ad.bitwiseEquipments) &&
        Objects.equals(this.originalTextBodyColor, ad.originalTextBodyColor) &&
        Objects.equals(this.originalTextInteriorColor, ad.originalTextInteriorColor) &&
        Objects.equals(this.originalTextLanguage, ad.originalTextLanguage) &&
        Objects.equals(this.teaser, ad.teaser) &&
        Objects.equals(this.dateNewRelevant, ad.dateNewRelevant) &&
        Objects.equals(this.isBehaveAsNew, ad.isBehaveAsNew) &&
        Objects.equals(this.dateNewFlagExpires, ad.dateNewFlagExpires) &&
        Objects.equals(this.seoDetail, ad.seoDetail) &&
        Objects.equals(this.dateTopListing, ad.dateTopListing) &&
        Objects.equals(this.insurance, ad.insurance) &&
        Objects.equals(this.showCashSentinel, ad.showCashSentinel) &&
        Objects.equals(this.images, ad.images) &&
        Objects.equals(this.documents, ad.documents) &&
        Objects.equals(this.videos, ad.videos) &&
        Objects.equals(this.logoId, ad.logoId) &&
        Objects.equals(this.logoText, ad.logoText) &&
        Objects.equals(this.logoUrl, ad.logoUrl) &&
        Objects.equals(this.logoImageUrl, ad.logoImageUrl) &&
        Objects.equals(this.logoTrackingUrl, ad.logoTrackingUrl) &&
        Objects.equals(this.isAccidentVehicle, ad.isAccidentVehicle) &&
        Objects.equals(this.isExchangeable, ad.isExchangeable) &&
        Objects.equals(this.isExport, ad.isExport) &&
        Objects.equals(this.isHandicapConverted, ad.isHandicapConverted) &&
        Objects.equals(this.isInspected, ad.isInspected) &&
        Objects.equals(this.isDirectImport, ad.isDirectImport) &&
        Objects.equals(this.isLocationExact, ad.isLocationExact) &&
        Objects.equals(this.isLeasable, ad.isLeasable) &&
        Objects.equals(this.isRacingVehicle, ad.isRacingVehicle) &&
        Objects.equals(this.isThrottleKitAvailable, ad.isThrottleKitAvailable) &&
        Objects.equals(this.isThrottleKitPossible, ad.isThrottleKitPossible) &&
        Objects.equals(this.isTuned, ad.isTuned) &&
        Objects.equals(this.equipment, ad.equipment) &&
        Objects.equals(this.longitude, ad.longitude) &&
        Objects.equals(this.latitude, ad.latitude) &&
        Objects.equals(this.comments, ad.comments) &&
        Objects.equals(this.internalComments, ad.internalComments) &&
        Objects.equals(this.hasWarranty, ad.hasWarranty) &&
        Objects.equals(this.warrantyInMonths, ad.warrantyInMonths) &&
        Objects.equals(this.warrantyDescription, ad.warrantyDescription) &&
        Objects.equals(this.isHighlighted, ad.isHighlighted);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, certificationCode, chassisCode, customerVehicleCode, userId, userTypeId, accountId, addressId, seller, status, dateCreated, dateModified, dateValidFrom, dateValidTo, isOnline, vehicleVisibilityId, vehicleTypeGroupId, vehicleTypeId, vehicleType, makeId, make, modelId, model, typeName, typeNameFull, dateLastInspection, firstRegYear, firstRegMonth, modelYear, modelMonth, conditionTypeId, conditionType, bodyTypeId, bodyType, segmentationTypeId, segmentationType, fuelTypeId, fuelType, transmissionTypeId, transmissionType, transmissionShaftId, transmissionShaftType, driveTypeId, driveType, pollutionNormTypeId, pollutionNormType, licenseCategoryTypeId, licenseCategoryType, consumptionRatingTypeId, consumptionRatingType, cylinderDesignTypeId, cylinderDesignType, bodyColorId, bodyColor, interiorColorId, interiorColor, price, priceNew, priceOriginal, km, consumptionCity, consumptionLand, consumptionTotal, consumptionGasCity, consumptionGasLand, consumptionGasTotal, consumptionPower, petrolEquivalent, co2Emission, co2EmissionAverage, co2EmissionPowerProduction, doors, seats, cylinders, gears, ccm, hp, kw, weightKerb, weightTotal, trailerLoadBreaked, length, width, height, bootHeight, bootWidth, bootLength, bootVolume, payLoad, wheelbase, axis, sleepingBerths, isBodyColorMetallic, bitwiseEquipments, originalTextBodyColor, originalTextInteriorColor, originalTextLanguage, teaser, dateNewRelevant, isBehaveAsNew, dateNewFlagExpires, seoDetail, dateTopListing, insurance, showCashSentinel, images, documents, videos, logoId, logoText, logoUrl, logoImageUrl, logoTrackingUrl, isAccidentVehicle, isExchangeable, isExport, isHandicapConverted, isInspected, isDirectImport, isLocationExact, isLeasable, isRacingVehicle, isThrottleKitAvailable, isThrottleKitPossible, isTuned, equipment, longitude, latitude, comments, internalComments, hasWarranty, warrantyInMonths, warrantyDescription, isHighlighted);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Ad {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    certificationCode: ").append(toIndentedString(certificationCode)).append("\n");
    sb.append("    chassisCode: ").append(toIndentedString(chassisCode)).append("\n");
    sb.append("    customerVehicleCode: ").append(toIndentedString(customerVehicleCode)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    userTypeId: ").append(toIndentedString(userTypeId)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    addressId: ").append(toIndentedString(addressId)).append("\n");
    sb.append("    seller: ").append(toIndentedString(seller)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
    sb.append("    dateModified: ").append(toIndentedString(dateModified)).append("\n");
    sb.append("    dateValidFrom: ").append(toIndentedString(dateValidFrom)).append("\n");
    sb.append("    dateValidTo: ").append(toIndentedString(dateValidTo)).append("\n");
    sb.append("    isOnline: ").append(toIndentedString(isOnline)).append("\n");
    sb.append("    vehicleVisibilityId: ").append(toIndentedString(vehicleVisibilityId)).append("\n");
    sb.append("    vehicleTypeGroupId: ").append(toIndentedString(vehicleTypeGroupId)).append("\n");
    sb.append("    vehicleTypeId: ").append(toIndentedString(vehicleTypeId)).append("\n");
    sb.append("    vehicleType: ").append(toIndentedString(vehicleType)).append("\n");
    sb.append("    makeId: ").append(toIndentedString(makeId)).append("\n");
    sb.append("    make: ").append(toIndentedString(make)).append("\n");
    sb.append("    modelId: ").append(toIndentedString(modelId)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    typeName: ").append(toIndentedString(typeName)).append("\n");
    sb.append("    typeNameFull: ").append(toIndentedString(typeNameFull)).append("\n");
    sb.append("    dateLastInspection: ").append(toIndentedString(dateLastInspection)).append("\n");
    sb.append("    firstRegYear: ").append(toIndentedString(firstRegYear)).append("\n");
    sb.append("    firstRegMonth: ").append(toIndentedString(firstRegMonth)).append("\n");
    sb.append("    modelYear: ").append(toIndentedString(modelYear)).append("\n");
    sb.append("    modelMonth: ").append(toIndentedString(modelMonth)).append("\n");
    sb.append("    conditionTypeId: ").append(toIndentedString(conditionTypeId)).append("\n");
    sb.append("    conditionType: ").append(toIndentedString(conditionType)).append("\n");
    sb.append("    bodyTypeId: ").append(toIndentedString(bodyTypeId)).append("\n");
    sb.append("    bodyType: ").append(toIndentedString(bodyType)).append("\n");
    sb.append("    segmentationTypeId: ").append(toIndentedString(segmentationTypeId)).append("\n");
    sb.append("    segmentationType: ").append(toIndentedString(segmentationType)).append("\n");
    sb.append("    fuelTypeId: ").append(toIndentedString(fuelTypeId)).append("\n");
    sb.append("    fuelType: ").append(toIndentedString(fuelType)).append("\n");
    sb.append("    transmissionTypeId: ").append(toIndentedString(transmissionTypeId)).append("\n");
    sb.append("    transmissionType: ").append(toIndentedString(transmissionType)).append("\n");
    sb.append("    transmissionShaftId: ").append(toIndentedString(transmissionShaftId)).append("\n");
    sb.append("    transmissionShaftType: ").append(toIndentedString(transmissionShaftType)).append("\n");
    sb.append("    driveTypeId: ").append(toIndentedString(driveTypeId)).append("\n");
    sb.append("    driveType: ").append(toIndentedString(driveType)).append("\n");
    sb.append("    pollutionNormTypeId: ").append(toIndentedString(pollutionNormTypeId)).append("\n");
    sb.append("    pollutionNormType: ").append(toIndentedString(pollutionNormType)).append("\n");
    sb.append("    licenseCategoryTypeId: ").append(toIndentedString(licenseCategoryTypeId)).append("\n");
    sb.append("    licenseCategoryType: ").append(toIndentedString(licenseCategoryType)).append("\n");
    sb.append("    consumptionRatingTypeId: ").append(toIndentedString(consumptionRatingTypeId)).append("\n");
    sb.append("    consumptionRatingType: ").append(toIndentedString(consumptionRatingType)).append("\n");
    sb.append("    cylinderDesignTypeId: ").append(toIndentedString(cylinderDesignTypeId)).append("\n");
    sb.append("    cylinderDesignType: ").append(toIndentedString(cylinderDesignType)).append("\n");
    sb.append("    bodyColorId: ").append(toIndentedString(bodyColorId)).append("\n");
    sb.append("    bodyColor: ").append(toIndentedString(bodyColor)).append("\n");
    sb.append("    interiorColorId: ").append(toIndentedString(interiorColorId)).append("\n");
    sb.append("    interiorColor: ").append(toIndentedString(interiorColor)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    priceNew: ").append(toIndentedString(priceNew)).append("\n");
    sb.append("    priceOriginal: ").append(toIndentedString(priceOriginal)).append("\n");
    sb.append("    km: ").append(toIndentedString(km)).append("\n");
    sb.append("    consumptionCity: ").append(toIndentedString(consumptionCity)).append("\n");
    sb.append("    consumptionLand: ").append(toIndentedString(consumptionLand)).append("\n");
    sb.append("    consumptionTotal: ").append(toIndentedString(consumptionTotal)).append("\n");
    sb.append("    consumptionGasCity: ").append(toIndentedString(consumptionGasCity)).append("\n");
    sb.append("    consumptionGasLand: ").append(toIndentedString(consumptionGasLand)).append("\n");
    sb.append("    consumptionGasTotal: ").append(toIndentedString(consumptionGasTotal)).append("\n");
    sb.append("    consumptionPower: ").append(toIndentedString(consumptionPower)).append("\n");
    sb.append("    petrolEquivalent: ").append(toIndentedString(petrolEquivalent)).append("\n");
    sb.append("    co2Emission: ").append(toIndentedString(co2Emission)).append("\n");
    sb.append("    co2EmissionAverage: ").append(toIndentedString(co2EmissionAverage)).append("\n");
    sb.append("    co2EmissionPowerProduction: ").append(toIndentedString(co2EmissionPowerProduction)).append("\n");
    sb.append("    doors: ").append(toIndentedString(doors)).append("\n");
    sb.append("    seats: ").append(toIndentedString(seats)).append("\n");
    sb.append("    cylinders: ").append(toIndentedString(cylinders)).append("\n");
    sb.append("    gears: ").append(toIndentedString(gears)).append("\n");
    sb.append("    ccm: ").append(toIndentedString(ccm)).append("\n");
    sb.append("    hp: ").append(toIndentedString(hp)).append("\n");
    sb.append("    kw: ").append(toIndentedString(kw)).append("\n");
    sb.append("    weightKerb: ").append(toIndentedString(weightKerb)).append("\n");
    sb.append("    weightTotal: ").append(toIndentedString(weightTotal)).append("\n");
    sb.append("    trailerLoadBreaked: ").append(toIndentedString(trailerLoadBreaked)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    bootHeight: ").append(toIndentedString(bootHeight)).append("\n");
    sb.append("    bootWidth: ").append(toIndentedString(bootWidth)).append("\n");
    sb.append("    bootLength: ").append(toIndentedString(bootLength)).append("\n");
    sb.append("    bootVolume: ").append(toIndentedString(bootVolume)).append("\n");
    sb.append("    payLoad: ").append(toIndentedString(payLoad)).append("\n");
    sb.append("    wheelbase: ").append(toIndentedString(wheelbase)).append("\n");
    sb.append("    axis: ").append(toIndentedString(axis)).append("\n");
    sb.append("    sleepingBerths: ").append(toIndentedString(sleepingBerths)).append("\n");
    sb.append("    isBodyColorMetallic: ").append(toIndentedString(isBodyColorMetallic)).append("\n");
    sb.append("    bitwiseEquipments: ").append(toIndentedString(bitwiseEquipments)).append("\n");
    sb.append("    originalTextBodyColor: ").append(toIndentedString(originalTextBodyColor)).append("\n");
    sb.append("    originalTextInteriorColor: ").append(toIndentedString(originalTextInteriorColor)).append("\n");
    sb.append("    originalTextLanguage: ").append(toIndentedString(originalTextLanguage)).append("\n");
    sb.append("    teaser: ").append(toIndentedString(teaser)).append("\n");
    sb.append("    dateNewRelevant: ").append(toIndentedString(dateNewRelevant)).append("\n");
    sb.append("    isBehaveAsNew: ").append(toIndentedString(isBehaveAsNew)).append("\n");
    sb.append("    dateNewFlagExpires: ").append(toIndentedString(dateNewFlagExpires)).append("\n");
    sb.append("    seoDetail: ").append(toIndentedString(seoDetail)).append("\n");
    sb.append("    dateTopListing: ").append(toIndentedString(dateTopListing)).append("\n");
    sb.append("    insurance: ").append(toIndentedString(insurance)).append("\n");
    sb.append("    showCashSentinel: ").append(toIndentedString(showCashSentinel)).append("\n");
    sb.append("    images: ").append(toIndentedString(images)).append("\n");
    sb.append("    documents: ").append(toIndentedString(documents)).append("\n");
    sb.append("    videos: ").append(toIndentedString(videos)).append("\n");
    sb.append("    logoId: ").append(toIndentedString(logoId)).append("\n");
    sb.append("    logoText: ").append(toIndentedString(logoText)).append("\n");
    sb.append("    logoUrl: ").append(toIndentedString(logoUrl)).append("\n");
    sb.append("    logoImageUrl: ").append(toIndentedString(logoImageUrl)).append("\n");
    sb.append("    logoTrackingUrl: ").append(toIndentedString(logoTrackingUrl)).append("\n");
    sb.append("    isAccidentVehicle: ").append(toIndentedString(isAccidentVehicle)).append("\n");
    sb.append("    isExchangeable: ").append(toIndentedString(isExchangeable)).append("\n");
    sb.append("    isExport: ").append(toIndentedString(isExport)).append("\n");
    sb.append("    isHandicapConverted: ").append(toIndentedString(isHandicapConverted)).append("\n");
    sb.append("    isInspected: ").append(toIndentedString(isInspected)).append("\n");
    sb.append("    isDirectImport: ").append(toIndentedString(isDirectImport)).append("\n");
    sb.append("    isLocationExact: ").append(toIndentedString(isLocationExact)).append("\n");
    sb.append("    isLeasable: ").append(toIndentedString(isLeasable)).append("\n");
    sb.append("    isRacingVehicle: ").append(toIndentedString(isRacingVehicle)).append("\n");
    sb.append("    isThrottleKitAvailable: ").append(toIndentedString(isThrottleKitAvailable)).append("\n");
    sb.append("    isThrottleKitPossible: ").append(toIndentedString(isThrottleKitPossible)).append("\n");
    sb.append("    isTuned: ").append(toIndentedString(isTuned)).append("\n");
    sb.append("    equipment: ").append(toIndentedString(equipment)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    internalComments: ").append(toIndentedString(internalComments)).append("\n");
    sb.append("    hasWarranty: ").append(toIndentedString(hasWarranty)).append("\n");
    sb.append("    warrantyInMonths: ").append(toIndentedString(warrantyInMonths)).append("\n");
    sb.append("    warrantyDescription: ").append(toIndentedString(warrantyDescription)).append("\n");
    sb.append("    isHighlighted: ").append(toIndentedString(isHighlighted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

