/**
 * AS24 API v4.1
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package abtlibrary.utils.as24ApiClient.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import abtlibrary.utils.as24ApiClient.model.AdEquipmentItem;
import java.util.ArrayList;
import java.util.List;


/**
 * AdEquipmentNotGrouped
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-21T15:07:04.675+07:00")
public class AdEquipmentNotGrouped   {
  @SerializedName("standard")
  private List<AdEquipmentItem> standard = new ArrayList<AdEquipmentItem>();

  @SerializedName("optional")
  private List<AdEquipmentItem> optional = new ArrayList<AdEquipmentItem>();

  @SerializedName("isFallback")
  private Boolean isFallback = null;

  public AdEquipmentNotGrouped standard(List<AdEquipmentItem> standard) {
    this.standard = standard;
    return this;
  }

  public AdEquipmentNotGrouped addStandardItem(AdEquipmentItem standardItem) {
    this.standard.add(standardItem);
    return this;
  }

   /**
   * Get standard
   * @return standard
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<AdEquipmentItem> getStandard() {
    return standard;
  }

  public void setStandard(List<AdEquipmentItem> standard) {
    this.standard = standard;
  }

  public AdEquipmentNotGrouped optional(List<AdEquipmentItem> optional) {
    this.optional = optional;
    return this;
  }

  public AdEquipmentNotGrouped addOptionalItem(AdEquipmentItem optionalItem) {
    this.optional.add(optionalItem);
    return this;
  }

   /**
   * Get optional
   * @return optional
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<AdEquipmentItem> getOptional() {
    return optional;
  }

  public void setOptional(List<AdEquipmentItem> optional) {
    this.optional = optional;
  }

  public AdEquipmentNotGrouped isFallback(Boolean isFallback) {
    this.isFallback = isFallback;
    return this;
  }

   /**
   * Get isFallback
   * @return isFallback
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsFallback() {
    return isFallback;
  }

  public void setIsFallback(Boolean isFallback) {
    this.isFallback = isFallback;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdEquipmentNotGrouped adEquipmentNotGrouped = (AdEquipmentNotGrouped) o;
    return Objects.equals(this.standard, adEquipmentNotGrouped.standard) &&
        Objects.equals(this.optional, adEquipmentNotGrouped.optional) &&
        Objects.equals(this.isFallback, adEquipmentNotGrouped.isFallback);
  }

  @Override
  public int hashCode() {
    return Objects.hash(standard, optional, isFallback);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdEquipmentNotGrouped {\n");
    
    sb.append("    standard: ").append(toIndentedString(standard)).append("\n");
    sb.append("    optional: ").append(toIndentedString(optional)).append("\n");
    sb.append("    isFallback: ").append(toIndentedString(isFallback)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

