/**
 * AS24 API v4.1
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package abtlibrary.utils.as24ApiClient.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * DealerPageRequest
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-21T15:07:04.675+07:00")
public class DealerPageRequest   {
  @SerializedName("accountId")
  private Integer accountId = null;

  @SerializedName("comments")
  private String comments = null;

  @SerializedName("requestorEmail")
  private String requestorEmail = null;

  @SerializedName("contactName")
  private String contactName = null;

  @SerializedName("phoneNumber")
  private String phoneNumber = null;

  @SerializedName("lng")
  private String lng = null;

  @SerializedName("wantsCopy")
  private Boolean wantsCopy = null;

  public DealerPageRequest accountId(Integer accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * Get accountId
   * @return accountId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getAccountId() {
    return accountId;
  }

  public void setAccountId(Integer accountId) {
    this.accountId = accountId;
  }

  public DealerPageRequest comments(String comments) {
    this.comments = comments;
    return this;
  }

   /**
   * Get comments
   * @return comments
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getComments() {
    return comments;
  }

  public void setComments(String comments) {
    this.comments = comments;
  }

  public DealerPageRequest requestorEmail(String requestorEmail) {
    this.requestorEmail = requestorEmail;
    return this;
  }

   /**
   * Get requestorEmail
   * @return requestorEmail
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRequestorEmail() {
    return requestorEmail;
  }

  public void setRequestorEmail(String requestorEmail) {
    this.requestorEmail = requestorEmail;
  }

  public DealerPageRequest contactName(String contactName) {
    this.contactName = contactName;
    return this;
  }

   /**
   * Get contactName
   * @return contactName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getContactName() {
    return contactName;
  }

  public void setContactName(String contactName) {
    this.contactName = contactName;
  }

  public DealerPageRequest phoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * Get phoneNumber
   * @return phoneNumber
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  public DealerPageRequest lng(String lng) {
    this.lng = lng;
    return this;
  }

   /**
   * Get lng
   * @return lng
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLng() {
    return lng;
  }

  public void setLng(String lng) {
    this.lng = lng;
  }

  public DealerPageRequest wantsCopy(Boolean wantsCopy) {
    this.wantsCopy = wantsCopy;
    return this;
  }

   /**
   * Get wantsCopy
   * @return wantsCopy
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getWantsCopy() {
    return wantsCopy;
  }

  public void setWantsCopy(Boolean wantsCopy) {
    this.wantsCopy = wantsCopy;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DealerPageRequest dealerPageRequest = (DealerPageRequest) o;
    return Objects.equals(this.accountId, dealerPageRequest.accountId) &&
        Objects.equals(this.comments, dealerPageRequest.comments) &&
        Objects.equals(this.requestorEmail, dealerPageRequest.requestorEmail) &&
        Objects.equals(this.contactName, dealerPageRequest.contactName) &&
        Objects.equals(this.phoneNumber, dealerPageRequest.phoneNumber) &&
        Objects.equals(this.lng, dealerPageRequest.lng) &&
        Objects.equals(this.wantsCopy, dealerPageRequest.wantsCopy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, comments, requestorEmail, contactName, phoneNumber, lng, wantsCopy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DealerPageRequest {\n");
    
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    requestorEmail: ").append(toIndentedString(requestorEmail)).append("\n");
    sb.append("    contactName: ").append(toIndentedString(contactName)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    lng: ").append(toIndentedString(lng)).append("\n");
    sb.append("    wantsCopy: ").append(toIndentedString(wantsCopy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

