/**
 * AS24 API v4.1
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package abtlibrary.utils.as24ApiClient.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import abtlibrary.utils.as24ApiClient.model.Model;
import java.util.ArrayList;
import java.util.List;


/**
 * Model
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-21T15:07:04.675+07:00")
public class Model   {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("makeId")
  private Integer makeId = null;

  @SerializedName("modelname")
  private String modelname = null;

  @SerializedName("models")
  private List<Model> models = new ArrayList<Model>();

  public Model id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Model makeId(Integer makeId) {
    this.makeId = makeId;
    return this;
  }

   /**
   * Get makeId
   * @return makeId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getMakeId() {
    return makeId;
  }

  public void setMakeId(Integer makeId) {
    this.makeId = makeId;
  }

  public Model modelname(String modelname) {
    this.modelname = modelname;
    return this;
  }

   /**
   * Get modelname
   * @return modelname
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getModelname() {
    return modelname;
  }

  public void setModelname(String modelname) {
    this.modelname = modelname;
  }

  public Model models(List<Model> models) {
    this.models = models;
    return this;
  }

  public Model addModelsItem(Model modelsItem) {
    this.models.add(modelsItem);
    return this;
  }

   /**
   * Get models
   * @return models
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Model> getModels() {
    return models;
  }

  public void setModels(List<Model> models) {
    this.models = models;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Model model = (Model) o;
    return Objects.equals(this.id, model.id) &&
        Objects.equals(this.makeId, model.makeId) &&
        Objects.equals(this.modelname, model.modelname) &&
        Objects.equals(this.models, model.models);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, makeId, modelname, models);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Model {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    makeId: ").append(toIndentedString(makeId)).append("\n");
    sb.append("    modelname: ").append(toIndentedString(modelname)).append("\n");
    sb.append("    models: ").append(toIndentedString(models)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

