/**
 * AS24 API v4.1
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package abtlibrary.utils.as24ApiClient.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import abtlibrary.utils.as24ApiClient.model.OptionFilter;
import java.util.ArrayList;
import java.util.List;


/**
 * MyListingVehicleStatus
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-21T15:07:04.675+07:00")
public class MyListingVehicleStatus   {
  @SerializedName("numberOfVehicles")
  private Integer numberOfVehicles = null;

  @SerializedName("label")
  private String label = null;

  @SerializedName("filters")
  private List<OptionFilter> filters = new ArrayList<OptionFilter>();

  public MyListingVehicleStatus numberOfVehicles(Integer numberOfVehicles) {
    this.numberOfVehicles = numberOfVehicles;
    return this;
  }

   /**
   * Get numberOfVehicles
   * @return numberOfVehicles
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getNumberOfVehicles() {
    return numberOfVehicles;
  }

  public void setNumberOfVehicles(Integer numberOfVehicles) {
    this.numberOfVehicles = numberOfVehicles;
  }

  public MyListingVehicleStatus label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public MyListingVehicleStatus filters(List<OptionFilter> filters) {
    this.filters = filters;
    return this;
  }

  public MyListingVehicleStatus addFiltersItem(OptionFilter filtersItem) {
    this.filters.add(filtersItem);
    return this;
  }

   /**
   * Get filters
   * @return filters
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<OptionFilter> getFilters() {
    return filters;
  }

  public void setFilters(List<OptionFilter> filters) {
    this.filters = filters;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MyListingVehicleStatus myListingVehicleStatus = (MyListingVehicleStatus) o;
    return Objects.equals(this.numberOfVehicles, myListingVehicleStatus.numberOfVehicles) &&
        Objects.equals(this.label, myListingVehicleStatus.label) &&
        Objects.equals(this.filters, myListingVehicleStatus.filters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numberOfVehicles, label, filters);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MyListingVehicleStatus {\n");
    
    sb.append("    numberOfVehicles: ").append(toIndentedString(numberOfVehicles)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

