/**
 * AS24 API v4.1
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package abtlibrary.utils.as24ApiClient.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import abtlibrary.utils.as24ApiClient.model.DealerPageDealer;
import abtlibrary.utils.as24ApiClient.model.MetaData;


/**
 * ResponseMessageDealerPageDealer
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-21T15:07:04.675+07:00")
public class ResponseMessageDealerPageDealer   {
  @SerializedName("result")
  private DealerPageDealer result = null;

  @SerializedName("metaData")
  private MetaData metaData = null;

  @SerializedName("href")
  private String href = null;

  @SerializedName("normalizedQuery")
  private String normalizedQuery = null;

  public ResponseMessageDealerPageDealer result(DealerPageDealer result) {
    this.result = result;
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @ApiModelProperty(example = "null", value = "")
  public DealerPageDealer getResult() {
    return result;
  }

  public void setResult(DealerPageDealer result) {
    this.result = result;
  }

  public ResponseMessageDealerPageDealer metaData(MetaData metaData) {
    this.metaData = metaData;
    return this;
  }

   /**
   * Get metaData
   * @return metaData
  **/
  @ApiModelProperty(example = "null", value = "")
  public MetaData getMetaData() {
    return metaData;
  }

  public void setMetaData(MetaData metaData) {
    this.metaData = metaData;
  }

   /**
   * Get href
   * @return href
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getHref() {
    return href;
  }

   /**
   * Get normalizedQuery
   * @return normalizedQuery
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getNormalizedQuery() {
    return normalizedQuery;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseMessageDealerPageDealer responseMessageDealerPageDealer = (ResponseMessageDealerPageDealer) o;
    return Objects.equals(this.result, responseMessageDealerPageDealer.result) &&
        Objects.equals(this.metaData, responseMessageDealerPageDealer.metaData) &&
        Objects.equals(this.href, responseMessageDealerPageDealer.href) &&
        Objects.equals(this.normalizedQuery, responseMessageDealerPageDealer.normalizedQuery);
  }

  @Override
  public int hashCode() {
    return Objects.hash(result, metaData, href, normalizedQuery);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseMessageDealerPageDealer {\n");
    
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    metaData: ").append(toIndentedString(metaData)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    normalizedQuery: ").append(toIndentedString(normalizedQuery)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

