/**
 * AS24 API v4.1
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v4.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package abtlibrary.utils.as24ApiClient.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * ThreeSixty
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-21T15:07:04.675+07:00")
public class ThreeSixty   {
  @SerializedName("v")
  private Integer v = null;

  @SerializedName("no")
  private Integer no = null;

  @SerializedName("width")
  private Integer width = null;

  @SerializedName("height")
  private Integer height = null;

  @SerializedName("md5HashZip")
  private String md5HashZip = null;

  public ThreeSixty v(Integer v) {
    this.v = v;
    return this;
  }

   /**
   * Get v
   * @return v
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getV() {
    return v;
  }

  public void setV(Integer v) {
    this.v = v;
  }

  public ThreeSixty no(Integer no) {
    this.no = no;
    return this;
  }

   /**
   * Get no
   * @return no
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getNo() {
    return no;
  }

  public void setNo(Integer no) {
    this.no = no;
  }

  public ThreeSixty width(Integer width) {
    this.width = width;
    return this;
  }

   /**
   * Get width
   * @return width
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getWidth() {
    return width;
  }

  public void setWidth(Integer width) {
    this.width = width;
  }

  public ThreeSixty height(Integer height) {
    this.height = height;
    return this;
  }

   /**
   * Get height
   * @return height
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getHeight() {
    return height;
  }

  public void setHeight(Integer height) {
    this.height = height;
  }

  public ThreeSixty md5HashZip(String md5HashZip) {
    this.md5HashZip = md5HashZip;
    return this;
  }

   /**
   * Get md5HashZip
   * @return md5HashZip
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMd5HashZip() {
    return md5HashZip;
  }

  public void setMd5HashZip(String md5HashZip) {
    this.md5HashZip = md5HashZip;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ThreeSixty threeSixty = (ThreeSixty) o;
    return Objects.equals(this.v, threeSixty.v) &&
        Objects.equals(this.no, threeSixty.no) &&
        Objects.equals(this.width, threeSixty.width) &&
        Objects.equals(this.height, threeSixty.height) &&
        Objects.equals(this.md5HashZip, threeSixty.md5HashZip);
  }

  @Override
  public int hashCode() {
    return Objects.hash(v, no, width, height, md5HashZip);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ThreeSixty {\n");
    
    sb.append("    v: ").append(toIndentedString(v)).append("\n");
    sb.append("    no: ").append(toIndentedString(no)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    md5HashZip: ").append(toIndentedString(md5HashZip)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

